version: 1
extends: "../.metricfs-map.yaml"
rules:
  - match:
      glob: "*.jsonl"
    decision: "any"
    mapper:
      kind: "multi_extract"
      emit:
        - object_type: "job"
          permission: "read"
          fields:
            namespace: "/event/job/namespace"
            name: "/event/job/name"
          canonical_template: "job:{namespace}/{name}"
      normalize:
        lowercase: true
        trim_slash: true
      fallback_paths:
        namespace:
          - "/event/facets/job/namespace"
        name:
          - "/event/facets/job/name"
    missing_resource_key: "ignore"
